# Generated by Django 4.0.6 on 2022-11-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.TextField(default='nnkjn'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Job Seeker', 'Job_seeker'), ('Company', 'Company')], default='Job_seeker', max_length=250),
        ),
    ]
