# Generated by Django 4.0.6 on 2022-11-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_first_name_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Job Seeker', 'Job_seeker'), ('Company', 'Company'), ('Admin', 'Admin')], default='Job_seeker', max_length=250),
        ),
    ]
