# Generated by Django 4.0.6 on 2022-12-01 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('tools', models.TextField()),
                ('feature', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_type', models.CharField(choices=[('Technical Skills', 'technical'), ('Soft Skills', 'soft')], default='technical', max_length=250)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='experience',
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(choices=[('Bachelor', 'bachelor'), ('Master', 'master'), ('Other', 'other')], default='bachelor', max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('start_year', models.DateTimeField()),
                ('end_year', models.DateTimeField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.course')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.education'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.skills'),
        ),
    ]
