# Generated by Django 4.0.6 on 2022-12-01 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_course_project_skills_remove_user_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('field_type', models.CharField(max_length=250)),
                ('position', models.CharField(choices=[('Senior', 'senior'), ('Junior', 'Junior'), ('Intern', 'intern'), ('Mid-Level', 'midlevel')], default='intern', max_length=250)),
                ('objectives', models.TextField()),
                ('start_year', models.DateTimeField()),
                ('end_year', models.DateTimeField()),
                ('projects', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.project')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='expereinces',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.experiences'),
        ),
    ]
