# Generated by Django 4.0.6 on 2022-12-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_experiences_user_expereinces'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
