# Generated by Django 4.0.6 on 2022-12-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
