# Generated by Django 4.0.6 on 2022-12-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_location_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='end_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='start_year',
            field=models.DateField(),
        ),
    ]
