# Generated by Django 4.0.6 on 2022-12-01 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_education_end_year_alter_education_start_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_education', to='account.education'),
        ),
    ]
