# Generated by Django 4.0.6 on 2022-12-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_remove_course_user_remove_education_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.ManyToManyField(to='account.course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.ManyToManyField(to='account.education'),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.ManyToManyField(to='account.experiences'),
        ),
        migrations.AlterField(
            model_name='user',
            name='project',
            field=models.ManyToManyField(to='account.project'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill',
            field=models.ManyToManyField(to='account.skills'),
        ),
    ]
