# Generated by Django 4.0.6 on 2022-12-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_remove_user_course_remove_user_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='experiences',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.ManyToManyField(to='account.course'),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.ManyToManyField(to='account.education'),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.ManyToManyField(to='account.experiences'),
        ),
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.ManyToManyField(to='account.project'),
        ),
        migrations.AddField(
            model_name='user',
            name='skill',
            field=models.ManyToManyField(to='account.skills'),
        ),
    ]
