# Generated by Django 4.0.6 on 2022-12-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_remove_course_user_remove_education_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_date',
            field=models.DateField(null=True),
        ),
    ]
