# Generated by Django 4.0.6 on 2022-12-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_user_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_date',
            field=models.DateField(null=True),
        ),
    ]
