# Generated by Django 4.0.6 on 2022-12-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_rename_payment_date_user_paymentend_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
