# Generated by Django 4.0.6 on 2022-12-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_user_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cv',
        ),
    ]
