# Generated by Django 4.0.6 on 2022-12-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_remove_user_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apply_attempt',
            field=models.IntegerField(max_length=250, null=True),
        ),
    ]
