# Generated by Django 4.0.6 on 2022-12-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile'),
        ),
    ]
