# Generated by Django 4.0.6 on 2022-12-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_termsandcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='termscondition',
            field=models.BooleanField(default=False),
        ),
    ]
