# Generated by Django 4.0.6 on 2022-12-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_location_alter_company_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
