# Generated by Django 4.0.6 on 2022-12-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_alter_company_location_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='termscondition',
            field=models.BooleanField(default=False),
        ),
    ]
