# Generated by Django 4.0.6 on 2022-11-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Bank Transfer', 'banktransfer'), ('Esewa', 'esewa'), ('Khalti', 'khalti'), ('PayPal', 'paypal'), ('Connect ips', 'Connectips')], default='paypal', max_length=250)),
                ('qrcode', models.FileField(null=True, upload_to='media')),
                ('name', models.CharField(max_length=250, null=True)),
                ('bank_details', models.TextField()),
                ('payment_screenshot', models.FileField(null=True, upload_to='media')),
                ('added_on', models.DateTimeField(null=True)),
                ('payment_status', models.CharField(choices=[('Bank Transfer', 'banktransfer'), ('Esewa', 'esewa'), ('Khalti', 'khalti'), ('PayPal', 'paypal'), ('Connect ips', 'Connectips')], default='unpaid', max_length=250)),
            ],
        ),
    ]
