# Generated by Django 4.0.6 on 2022-11-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'paid'), ('Un Paid', 'unpaid'), ('Partial Payment', 'patial')], default='unpaid', max_length=250),
        ),
    ]
