# Generated by Django 4.0.6 on 2022-12-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0003_dashboard_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='user',
            new_name='send_to',
        ),
    ]
