# Generated by Django 4.0.6 on 2022-12-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0004_rename_user_dashboard_send_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='payment_screenshot',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
