# Generated by Django 4.0.6 on 2022-12-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0005_alter_dashboard_payment_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='payment_screenshot',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
