# Generated by Django 4.0.6 on 2022-12-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0006_alter_dashboard_payment_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='apply_attempt',
            field=models.IntegerField(default=0),
        ),
    ]
