# Generated by Django 4.0.6 on 2022-12-04 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboardapp', '0007_dashboard_apply_attempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='name',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
