# Generated by Django 4.0.6 on 2022-12-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0010_dommy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'paid'), ('Un Paid', 'unpaid'), ('Partial Payment', 'patial')], default='Un Paid', max_length=250),
        ),
    ]
