# Generated by Django 4.0.6 on 2022-11-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=250, null=True)),
                ('cat_img', models.FileField(null=True, upload_to='media')),
                ('cat_desc', models.TextField(max_length=250, null=True)),
                ('added_on', models.DateTimeField(null=True)),
            ],
        ),
    ]
