# Generated by Django 4.0.6 on 2022-11-28 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat_img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat_name',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('image', models.FileField(null=True, upload_to='media')),
                ('description', models.TextField(max_length=250, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.category')),
            ],
        ),
    ]
