# Generated by Django 4.0.6 on 2022-12-12 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('image', models.FileField(null=True, upload_to='media')),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat_img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('Digital Work', 'digital'), ('Field Work', 'field')], default='digital', max_length=250),
        ),
        migrations.AddField(
            model_name='category',
            name='post_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('image', models.FileField(null=True, upload_to='media')),
                ('description', models.TextField(max_length=250, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('salary_range', models.CharField(max_length=250, null=True)),
                ('job_type', models.CharField(choices=[('Part Time', 'parttime'), ('Full Time', 'fulltime'), ('Freelancing', 'freelance'), ('Remote', 'remote')], default='fulltime', max_length=250)),
                ('no_of_vacancy', models.CharField(max_length=250, null=True)),
                ('knowledge', models.TextField(null=True)),
                ('skill', models.TextField(null=True)),
                ('abilities', models.TextField(null=True)),
                ('education', models.TextField(null=True)),
                ('expereince', models.TextField(null=True)),
                ('application_date', models.DateField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catjob', to='jobapp.category')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.location')),
                ('post_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('cv', models.FileField(null=True, upload_to='media')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvjob', to='jobapp.job')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
