# Generated by Django 4.0.6 on 2022-12-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_location_rename_cat_desc_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posted_date',
            field=models.DateField(null=True),
        ),
    ]
