# Generated by Django 4.0.6 on 2022-12-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_rename_cat_desc_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cv',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
