# Generated by Django 4.0.6 on 2022-12-17 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_job_posted_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancingSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('image', models.FileField(null=True, upload_to='media')),
                ('description', models.TextField(max_length=250, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.category')),
            ],
        ),
    ]
