# Generated by Django 4.0.6 on 2022-12-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_maincategory_delete_freelancingsubcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincategory',
            name='name',
        ),
        migrations.AddField(
            model_name='maincategory',
            name='category_type',
            field=models.CharField(choices=[('Digital Work', 'digital'), ('Field Work', 'field'), ('Freelancing Work', 'freelancing')], default='digital', max_length=250),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('Digital Work', 'digital'), ('Field Work', 'field'), ('Freelancing Work', 'freelancing')], default='digital', max_length=250),
        ),
    ]
