# Generated by Django 4.0.6 on 2022-12-24 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_remove_maincategory_name_maincategory_category_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.maincategory'),
        ),
    ]
