# Generated by Django 4.0.6 on 2022-12-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_alter_cvupload_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvupload',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
