# Generated by Django 4.0.6 on 2022-12-04 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_cvupload_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvupload',
            name='job',
        ),
        migrations.AddField(
            model_name='cvupload',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvjob', to='jobapp.category'),
        ),
    ]
