# Generated by Django 4.0.6 on 2022-12-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_remove_cvupload_job_cvupload_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvupload',
            name='category',
        ),
        migrations.AddField(
            model_name='cvupload',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvjob', to='jobapp.job'),
        ),
    ]
