# Generated by Django 4.0.6 on 2022-12-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0011_remove_cvupload_name_cvupload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvupload',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
