# Generated by Django 4.0.6 on 2022-12-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0012_cvupload_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvupload',
            name='status',
            field=models.CharField(choices=[('Accepted', 'accepted'), ('Rejected', 'rejected'), ('Not Viewed', 'notview')], default='notview', max_length=250),
        ),
    ]
