# Generated by Django 4.0.6 on 2022-12-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0013_cvupload_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvupload',
            name='status',
        ),
    ]
