# Generated by Django 4.0.6 on 2022-12-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0014_remove_cvupload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
