# Generated by Django 4.0.6 on 2022-12-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0015_job_date_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary_range',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
