# Generated by Django 4.0.6 on 2022-12-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0016_job_salary_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Part Time', 'parttime'), ('Full Time', 'fulltime'), ('Freelancing Time', 'freelance')], default='fulltime', max_length=250),
        ),
    ]
