# Generated by Django 4.0.6 on 2022-12-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0018_alter_job_options_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Part Time', 'parttime'), ('Full Time', 'fulltime'), ('Freelancing', 'freelance'), ('Remote', 'remote')], default='fulltime', max_length=250),
        ),
    ]
