# Generated by Django 4.0.6 on 2022-12-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0019_alter_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vacancy',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
