# Generated by Django 4.0.6 on 2022-12-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0022_job_application_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='abilities',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='education',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='expereince',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='knowledge',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skill',
            field=models.TextField(null=True),
        ),
    ]
